baseURL: https://kushsharma924.github.io/
languageCode: en-us
build:
  writeStats: true
params:
  title: Kush Sharma
  author: Kush Sharma
  description: 
  copyright: >-
    Powered by [Hugo](https://gohugo.io/) & deployed on
    [GitHub Pages](https://pages.github.com/).
  theme:
    mainTheme: dark
    showAttribute: false
    singlePage: true
  # TODO
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="shortcut icon" href="favicon.ico">
  profile:
    name: "Kush Sharma"
    tagline: 
    location: "Turing Scholar at UT Austin"
    photo: profile.jpg
  social:
    title: Links
    list:
      - icon: fab fa-linkedin
        url: "https://linkedin.com/in/ks924"
        title: LinkedIn
      - icon: fab fa-github
        url: "https://github.com/kushsharma924"
        title: GitHub
      - icon: fas fa-file-alt
        url: "https://drive.google.com/file/d/1rXXhHWV43D7KVfm63CJC4nG_p1nYvRzQ/view?usp=sharing"
        title: Resume
  showInAccordion:
    - item: aboutme
      # expand: true
    - item: education
    - item: experience
    # - item: publication
    - item: project
    - item: skill
    - item: hobby
  aboutme:
    title: About Me
    icon: fas fa-user
    description: Hi, I'm Kush. I study computer science and math at UT Austin through the Turing Scholars honors program . I'm interested in theoretical CS (specifically cryptography) and the intersection between math, software, and finance. Outside of school, I enjoy biking, reading, traveling, and playing cricket. Feel free to reach me at `kush.sharma@utexas.edu`.
  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: B.S. in Computer Science, Turing Scholars Honors
        college: The University of Texas at Austin
        dates: May 2027
      - degree: B.S. in Mathematics
        college: The University of Texas at Austin
        dates: May 2027
  experience:
    title: Experiences
    icon: fas fa-briefcase
    list:
      - position: Software Engineering Intern
        dates: May 2025 - August 2025
        company: ProfitAngles
        details: |1-
          - Contributed to a financial advising web app focused on delivering personalized, user-centric investing insights
          - Engineered an LLM to process natural language queries on financial data, enabling intuitive user interaction
          - Optimized complex database queries for financial metrics, reducing query execution time by over 25%
          - Designed a streamlined dashboard interface using ReactJS, improving information accessibility by over 40%
      - position: Machine Learning Research Intern
        dates: May 2023 - August 2023
        company: The University of Texas at Dallas
        details: |1-
          - Researched under Dr. Yunhui Guo on the design and analysis of active learning algorithms for open-set annotation
          - Pioneered a novel active learning algorithm combining uncertainty and diversity-based methods
          - Reduced training time by 21% compared to state of the art, achieving a robust accuracy of 98.1%
          - Implemented LeNet and ResNet architectures; created Matplotlib script to compare precision and recall
      - position: Student Technician
        dates: August 2024 - Present
        company: The University of Texas at Austin
        details: |1-
          - Resolved networking-related IT tickets, ensuring 95% device connectivity across multiple campus locations
          - Managed routers, switches, static IP address allocation, port activations, and VLAN segmentation

  # publication:
  #   title: Publications
  #   icon: fas fa-book
  #   format:
  #     - date
  #     - title
  #     - authors
  #     - journal
  #   types:
  #     - Journal Articles
  #     - Proceedings
  #   list:
  #     - title: >-
  #         Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
  #         eiusmod tempor incididunt ut labore et dolore magna aliqua.
  #       authors: "F Last, F Second, P secondary"
  #       date: "2018"
  #       journal: "Journal of Field 52 (16), 9033-9044"
  #       url: "#"
  #       type: Journal Articles
  #     - title: >-
  #         Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
  #         eiusmod tempor incididunt ut labore et dolore magna aliqua.
  #       authors: "F Last, F Second, P secondary"
  #       date: "2018"
  #       journal: "Journal of Field 52 (16), 9033-9044"
  #       url: "#"
  #       type: Journal Articles
  #     - title: >-
  #         Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
  #         eiusmod tempor incididunt ut labore et dolore magna aliqua.
  #       authors: "F Last, F Second, P secondary"
  #       date: "2018"
  #       journal: "Journal of Field 52 (16), 9033-9044"
  #       url: "#"
  #       type: Proceedings
  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
      - title: UIL CS Contest Guide – cs240
        description: >-
          1. -> Created a full-stack NuxtJS web application used by over 500 active users preparing for the UIL CS Contest

          2. -> Utilized Tailwind CSS to design a streamlined UI with custom components for footers, navbars, and sidebars

          3. -> Engineered a REST API backend using TypeScript and stored user login data using MongoDB
      - title: Compiler + LLVM IR Frontend
        description: >-
          1. -> Implemented a full compiler for a custom language supporting conditionals, iteration, and first-class functions

          2. -> Built an LLVM IR frontend for an extended spec, adding custom data types, arrays, and user-defined structs
      - title: Pipelined Processor
        description: >-
          1. -> Designed a 5 stage pipelined processor for a custom ISA with mov, load/store, and branch instructions

          2. -> Implemented pipelining optimizations such as flushing, stalling, and branch prediction to deal with hazards
      - title: Multiprocess Heap
        description: >-
          1. -> Designed and implemented a shared heap, enabling concurrent malloc, realloc, and free across multiple processes
      - title: ARM Emulator
        description: >-
          1. -> Built a functioning emulator for a subset of ARM including load/store, cbnz, and orr instructions
  skill:
    title: Skills
    icon: fas fa-cogs
    list:
      - skill: Programming Languages -> Java, C, C++, Python, Swift, JavaScript, TypeScript, HTML/CSS
      - skill: Libraries & Frameworks -> ReactJS, NodeJS, NuxtJS, Tailwind, PyTorch, NumPy, Pandas, Matplotlib, STL
      - skill: Developer Tools -> AWS (Amplify), MongoDB, Xcode, Markdown, Git, GitHub
  hobby:
    title: Awards
    icon: fas fa-award
    list:
      - hobby: CS Awards -> USA Computing Olympiad Gold Division Qualifer (Top 10%), Texas UIL CS State Qualifier (Top 1%)
      - hobby: Other Awards -> AIME Qualifier, AMC 12A Distinction (Top 5%), National Merit Scholarship Finalist (Top 1%)
