baseURL: https://kushsharma924.github.io/
languageCode: en-us
build:
  writeStats: true
params:
  title: Kush Sharma
  author: Kush Sharma
  description: 
  copyright: >-
    Powered by [Hugo](https://gohugo.io/) & deployed on
    [GitHub Pages](https://pages.github.com/).
  theme:
    mainTheme: dark
    showAttribute: false
    singlePage: true
  # TODO
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="shortcut icon" href="favicon.ico">
  profile:
    name: "Kush Sharma"
    tagline: 
    location: "Turing Scholar at UT Austin"
    photo: profile.jpg
  social:
    title: Links
    list:
      - icon: fab fa-linkedin
        url: "https://linkedin.com/in/ks924"
        title: LinkedIn
      - icon: fab fa-github
        url: "https://github.com/kushsharma924"
        title: GitHub
      - icon: fas fa-file-alt
        url: "https://drive.google.com/file/d/16EV0GLYJ_VZHz_rOGmVIT1pdJ8y8aNlE/view?usp=sharing"
        title: Resume
  showInAccordion:
    - item: aboutme
      # expand: true
    - item: education
    - item: experience
    # - item: publication
    - item: project
    - item: skill
    - item: hobby
  aboutme:
    title: About Me
    icon: fas fa-user
    description: Hi, I'm Kush, a Turing Scholar at The University of Texas at Austin also pursuing a double major in Math. I'm interested in Theory, Machine Learning, and the intersection between Software and Finance. Outside of CS, I enjoy biking, reading, traveling, and trying out new food. Feel free to reach me at `kush.sharma@utexas.edu`.
  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: B.S. in Computer Science, Turing Scholars Honors
        college: The University of Texas at Austin
        dates: Expected May 2026
      - degree: B.S. in Mathematics
        college: The University of Texas at Austin
        dates: Expected May 2026
  experience:
    title: Experiences
    icon: fas fa-briefcase
    list:
      - position: Machine Learning Research Intern
        dates: May 2023 - August 2023
        company: The University of Texas at Dallas
        details: |1-
          - Worked in a team of 5 on the design and analysis of active learning algorithms for open-set annotation
          - Performed a comprehensive literature review on active learning methods such as BADGE and HUDS
          - Implemented the random and uncertainty sampling methods on the CIFAR-10 and CIFAR-100 datasets
          - Trained convolutional neural network architectures like LeNet and ResNet using stochastic gradient descent
          - Developed a Matplotlib plotting script to compare accuracy, precision, recall, computational efficiency, and speed
  # publication:
  #   title: Publications
  #   icon: fas fa-book
  #   format:
  #     - date
  #     - title
  #     - authors
  #     - journal
  #   types:
  #     - Journal Articles
  #     - Proceedings
  #   list:
  #     - title: >-
  #         Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
  #         eiusmod tempor incididunt ut labore et dolore magna aliqua.
  #       authors: "F Last, F Second, P secondary"
  #       date: "2018"
  #       journal: "Journal of Field 52 (16), 9033-9044"
  #       url: "#"
  #       type: Journal Articles
  #     - title: >-
  #         Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
  #         eiusmod tempor incididunt ut labore et dolore magna aliqua.
  #       authors: "F Last, F Second, P secondary"
  #       date: "2018"
  #       journal: "Journal of Field 52 (16), 9033-9044"
  #       url: "#"
  #       type: Journal Articles
  #     - title: >-
  #         Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
  #         eiusmod tempor incididunt ut labore et dolore magna aliqua.
  #       authors: "F Last, F Second, P secondary"
  #       date: "2018"
  #       journal: "Journal of Field 52 (16), 9033-9044"
  #       url: "#"
  #       type: Proceedings
  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
      - title: Meal Planner App – Flavor Finder
        url: "https://github.com/kushsharma924/meal-planner-app"
        description: >-
          1. -> Developed a full-stack recipe finder web app using a REST API and displaying results in a single-page application

          2. -> Designed a streamlined React frontend using navbars, drop downs, recipe cards, and other custom components

          3. -> Continuously deployed application to over 50 users utilizing AWS Amplify with over 1000 sitewide searches

          4. -> Achieved a user satisfaction rate of 91% on accuracy of recipe results, with an average user rating of 4.6/5.0
      - title: UIL CS Contest Guide – cs240.org
        url: "cs240.org"
        description: >-
          1. -> Created a full-stack NuxtJS web application used by over 500 active users preparing for the UIL CS Contest

          2. -> Devoleped a robust, organized core CS curriculum by publishing detailed topic-wise tutorials in Markdown

          3. -> Utilized Tailwind CSS to design a streamlined UI with custom components for footers, navbars, and sidebars

          4. -> Developed a REST API backend using TypeScript and stored data using MongoDB and SHA256 hashing
      - title: Swift Mobile App – Mynance
        url: "https://github.com/kushSharma924/mynance"
        description: >-
          1. -> Developed a Swift-based mobile application to track financial transactions and improve money management

          2. -> Designed UI using Interface Builder with AutoLayout constraints for graceful orientation handling

          3. -> Utilized Swift’s UserDefaults Database to persistently store user’s financial data to the disk

          4. -> Utilized table views, segues, and MVC architecture to provide a user-friendly interface and project structure
      - title: Active Learning Algorithm – Dynamic Sampling
        url: "https://github.com/kushSharma924/dynamic-sampling"
        description: >-
          1. -> Designed a novel active learning algorithm combining uncertainty and diversity-based methods

          2. -> Implemented a convolutional neural network to classify handwritten digits on the MNIST dataset

          3. -> Reduced total training time by 21% when compared to using solely uncertainty or diversity sampling

          4. -> Acheived a final accuracy of 98.1% after turning hyperparameters like learning rate, kernel size, and epoch count
  skill:
    title: Skills
    icon: fas fa-cogs
    list:
      - skill: Programming Languages -> Java, C/C++, Python, Swift, JavaScript, TypeScript, HTML/CSS
      - skill: Libraries & Frameworks -> ReactJS, NodeJS, NuxtJS, Tailwind, PyTorch, NumPy, Pandas, Matplotlib, STL
      - skill: Developer Tools -> AWS (Amplify), MongoDB, Xcode, Markdown, Git/GitHub
  hobby:
    title: Awards
    icon: fas fa-award
    list:
      - hobby: Computer Science Awards -> USA Computing Olympiad Silver Division Qualifer, Texas UIL CS State Qualifier
      - hobby: Other Awards -> AIME Qualifier, AMC 12A Distinction (Top 5%), National Merit Scholarship Finalist (Top 1%)
